/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TechQuizApp.gui;

import TechQuizApp.Pojo.UserProfile;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class ViewScoresFrame extends javax.swing.JFrame {

    /**
     * Creates new form ViewScoresFrame
     */
    public ViewScoresFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Tech Quiz App");
        lblUserName.setText("Hello "+UserProfile.getUsername());
        
        lblViewScore.setOpaque(true);
        lblViewScore.setBackground(new Color(0,0,51));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblUserName = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        lblSetPaper = new javax.swing.JLabel();
        lblViewScore = new javax.swing.JLabel();
        lblEditPaper = new javax.swing.JLabel();
        lblRegisterStudent = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jrSingleScore = new javax.swing.JRadioButton();
        jrAllScores = new javax.swing.JRadioButton();
        btnDoTask = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));

        lblUserName.setBackground(new java.awt.Color(255, 255, 255));
        lblUserName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserName.setText("Hello User");

        lblLogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogout.setText("Logout");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });

        lblSetPaper.setBackground(new java.awt.Color(0, 0, 0));
        lblSetPaper.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSetPaper.setForeground(new java.awt.Color(255, 255, 255));
        lblSetPaper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSetPaper.setText("Set paper");
        lblSetPaper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSetPaperMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSetPaperMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSetPaperMouseExited(evt);
            }
        });

        lblViewScore.setBackground(new java.awt.Color(0, 0, 0));
        lblViewScore.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblViewScore.setForeground(new java.awt.Color(255, 255, 255));
        lblViewScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewScore.setText("View Score");
        lblViewScore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewScoreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblViewScoreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblViewScoreMouseExited(evt);
            }
        });

        lblEditPaper.setBackground(new java.awt.Color(0, 0, 0));
        lblEditPaper.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEditPaper.setForeground(new java.awt.Color(255, 255, 255));
        lblEditPaper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditPaper.setText("Edit Paper");
        lblEditPaper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditPaperMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEditPaperMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEditPaperMouseExited(evt);
            }
        });

        lblRegisterStudent.setBackground(new java.awt.Color(0, 0, 0));
        lblRegisterStudent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRegisterStudent.setForeground(new java.awt.Color(255, 255, 255));
        lblRegisterStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegisterStudent.setText("Register Student");
        lblRegisterStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegisterStudentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegisterStudentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegisterStudentMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TechQuizApp/images/stud1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblSetPaper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblViewScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblEditPaper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblRegisterStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel7)
                .addContainerGap(27, Short.MAX_VALUE))
            .addComponent(lblUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSetPaper, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEditPaper, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lblRegisterStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblViewScore, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Scores Panel");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Make a Choice");

        jrSingleScore.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrSingleScore);
        jrSingleScore.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrSingleScore.setForeground(new java.awt.Color(0, 51, 255));
        jrSingleScore.setText("View Scores of Single Student");
        jrSingleScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrSingleScoreActionPerformed(evt);
            }
        });

        jrAllScores.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrAllScores);
        jrAllScores.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrAllScores.setForeground(new java.awt.Color(0, 51, 255));
        jrAllScores.setText("View All Scores");

        btnDoTask.setBackground(new java.awt.Color(255, 255, 255));
        btnDoTask.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDoTask.setForeground(new java.awt.Color(0, 51, 153));
        btnDoTask.setText("Do Task");
        btnDoTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDoTaskMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDoTaskMouseExited(evt);
            }
        });
        btnDoTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jrAllScores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jrSingleScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 63, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDoTask, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jrSingleScore)
                .addGap(18, 18, 18)
                .addComponent(jrAllScores)
                .addGap(86, 86, 86)
                .addComponent(btnDoTask, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // TODO add your handling code here:
        this.dispose();
        LoginFrame loginFrame = new LoginFrame();
        loginFrame.setVisible(true);
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        lblLogout.setForeground(Color.white);
        Font f = new Font("Tahoma",Font.ITALIC,14);
        lblLogout.setFont(f);
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        // TODO add your handling code here:
        lblLogout.setForeground(new Color(255,255,255));
        Font f = new Font("Tahoma",Font.BOLD,14);
        lblLogout.setFont(f);
    }//GEN-LAST:event_lblLogoutMouseExited

    private void lblSetPaperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetPaperMouseClicked
        SetPaperFrame spf = new SetPaperFrame();
        this.dispose();
        spf.setVisible(true);
    }//GEN-LAST:event_lblSetPaperMouseClicked

    private void lblSetPaperMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetPaperMouseEntered
        lblSetPaper.setOpaque(true);
        lblSetPaper.setBackground(new Color(0,0,51));
    }//GEN-LAST:event_lblSetPaperMouseEntered

    private void lblSetPaperMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetPaperMouseExited
        lblSetPaper.setOpaque(true);
        lblSetPaper.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_lblSetPaperMouseExited

    private void lblViewScoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewScoreMouseClicked
        ViewScoresFrame vsf = new ViewScoresFrame();
        this.dispose();
        vsf.setVisible(true);
    }//GEN-LAST:event_lblViewScoreMouseClicked

    private void lblViewScoreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewScoreMouseEntered
        
    }//GEN-LAST:event_lblViewScoreMouseEntered

    private void lblViewScoreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewScoreMouseExited
        
    }//GEN-LAST:event_lblViewScoreMouseExited

    private void lblEditPaperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditPaperMouseClicked
        EditPaperFrame epf = new EditPaperFrame();
        this.dispose();
        epf.setVisible(true);
    }//GEN-LAST:event_lblEditPaperMouseClicked

    private void lblEditPaperMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditPaperMouseEntered
        lblEditPaper.setOpaque(true);
        lblEditPaper.setBackground(new Color(0,0,51));
    }//GEN-LAST:event_lblEditPaperMouseEntered

    private void lblEditPaperMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditPaperMouseExited
        lblEditPaper.setOpaque(true);
        lblEditPaper.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_lblEditPaperMouseExited

    private void lblRegisterStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterStudentMouseClicked
        RegisterStudentFrame rsf = new RegisterStudentFrame();
        this.dispose();
        rsf.setVisible(true);
    }//GEN-LAST:event_lblRegisterStudentMouseClicked

    private void lblRegisterStudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterStudentMouseEntered
        lblRegisterStudent.setOpaque(true);
        lblRegisterStudent.setBackground(new Color(0,0,51));
    }//GEN-LAST:event_lblRegisterStudentMouseEntered

    private void lblRegisterStudentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterStudentMouseExited
        lblRegisterStudent.setOpaque(true);
        lblRegisterStudent.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_lblRegisterStudentMouseExited

    private void jrSingleScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrSingleScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrSingleScoreActionPerformed

    private void btnDoTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoTaskActionPerformed
        if(validateInputs()==false)
        {
            JOptionPane.showMessageDialog(null, "Please Choose an Option","Error!",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(jrSingleScore.isSelected())
        {
            ViewSingleStudentScoreFrame singleScoreFrame = new ViewSingleStudentScoreFrame();
            singleScoreFrame.setVisible(true);
        }
        else
        {
            ViewAllStudentsScoresFrame allScoreFrame=new ViewAllStudentsScoresFrame();
            allScoreFrame.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnDoTaskActionPerformed

    private void btnDoTaskMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoTaskMouseEntered
        btnDoTask.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_btnDoTaskMouseEntered

    private void btnDoTaskMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoTaskMouseExited
        btnDoTask.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnDoTaskMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewScoresFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewScoresFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewScoresFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewScoresFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewScoresFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoTask;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jrAllScores;
    private javax.swing.JRadioButton jrSingleScore;
    private javax.swing.JLabel lblEditPaper;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblRegisterStudent;
    private javax.swing.JLabel lblSetPaper;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblViewScore;
    // End of variables declaration//GEN-END:variables
private boolean validateInputs()
    {
        if(jrSingleScore.isSelected() == false && jrAllScores.isSelected()==false)
            return false;
        else
            return true;
    }

}
